### ISSUE TITLE
File type field error

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#135] opened 2020-07-06 12:08 UTC
When you try to edit a previously created file type field, it doesn't allow it.

I use moodle 3.8.3
Attachment screenshot.
![cap-10](https://user-images.githubusercontent.com/61394948/86591625-33002780-bf92-11ea-8258-3e3c4af38a5e.png)

Regards

**Comment by michaelpollak** [comment] 2020-07-06 14:39
Good to hear from you, I hope you are doing fine. Thanks for the issue report.
I tested your issue but was not able to reproduce either in 3.6 or 3.8. Can you provide some more detail?

I tested to
1) set up an instance with a field type file
2) add an entry and attach a file, save
3) edit an entry and delete file, save
4) add an entry and attach a file, save
5) edit an entry and attach second file, save

All of these procedures worked flawless in both moodle versions. Do you edit a special file maybe? 
Thank you.

**Comment by jesusman111** [comment] 2020-07-06 16:04
Hello Michael:

I have been investigating and have seen that this occurs when using a filter with the option "Group by" (Attachments screenshots).

I'm also glad to talk to you.

By the way, do you know when the next version of datalynx will be released?

Thank you so much for everything.

Best regards

![cap-11](https://user-images.githubusercontent.com/61394948/86614319-1b856680-bfb3-11ea-8a00-c6dd70a5cd38.png)

![cap-12](https://user-images.githubusercontent.com/61394948/86614339-25a76500-bfb3-11ea-8970-274ab306d638.png)

**Comment by michaelpollak** [comment] 2020-07-07 10:00
The filter does not effect the update process, so I doubt this is the culprit.

Sadly I cannot provide you more information on the next release, I am sure David is working on it. Currently I am building the moodle mobile (the Smartphone App) integration and I would think when this is done an update will be released.

**Comment by jesusman111** [comment] 2020-07-08 17:06
I have tested in different environments and the pattern always plays.
When a filter exists that uses the group by field, editing the file type field fails.

Attached new screenshots

Very thankful
![cap-16](https://user-images.githubusercontent.com/61394948/86948894-21637f00-c14e-11ea-854a-9fbe7cb7af48.png)
![cap-17](https://user-images.githubusercontent.com/61394948/86948901-245e6f80-c14e-11ea-9b16-5c17fb93f0f2.png)
![cap18](https://user-images.githubusercontent.com/61394948/86948907-26283300-c14e-11ea-8196-df9bcc7112a8.png)

**Comment by michaelpollak** [comment] 2020-07-13 09:25
Sorry but I am not able to reproduce this, hope you will find the culprit and let us know :)

**Comment by jesusman111** [comment] 2020-07-13 10:01
It may be because of thema.
Use Moove

Thank you very much

**Comment by dasistwas** [comment] 2020-07-13 10:02
Looks like a JavaScript problem. Does the loading icon always stay is shown on the screenshot?

**Comment by jesusman111** [comment] 2020-07-13 10:26
Yes, when using the filter by group.

If this type of filter is not used, it appears correctly.

**Comment by michaelpollak** [comment] 2020-10-28 13:08
Can't reproduce thus closing the issue. Let us know if you stumble into it again, thanks.

**Closed by michaelpollak** 2020-10-28 13:08 UTC
